version: '3.9'
services:
  app:
    container_name: golang_container
    build: .
    ports:
      - "50051:50051"
    environment:
      - DB_HOST=postgresdb
      - DB_USER=gk
      - DB_PASS=1234
      - DB_NAME=coindata
      - DB_PORT=5432
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    depends_on:
      - postgresdb
      - jaeger
    networks:
      - backend

  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=gk
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=coindata
    ports:
      - "5436:5432"
    networks:
      - backend

  jaeger:
    image: jaegertracing/all-in-one:1.46
    container_name: jaeger_container
    ports:
      - "16685:16685"
      - "16686:16686"
      - "14268:14268"
    networks:
      - backend

networks:
  backend:
    driver: bridge
